### ISSUE TITLE
Where do I enter my link ok path to m3u?

### ISSUE THREAD

**Issue by MEMediaEntertainment** [peterpt/IPTV-CHECK#10]
I've try so many things, I'm getting...

"***************** ~/Downloads/iptv-check/IPTV-CHECK (master)
$ bash iptv-check
iptv-check: line 3: Beta: command not found
 IPTV-Check Tool
 -------------------------------------
 http://github.com/peterpt
 -------------------------------------

 Example for remote list to check :
 iptv-check http://someurl/somelist.m3u

 Example for local list to check :
 iptv-check /root/mylist.m3u

        NOTE
This tool will download 2 seconds of each stream to check
if every link in m3u file is valid , so , it may take a while
 -------------------------------------

*****************  ~/Downloads/iptv-check/IPTV-CHECK (master)
$ bash iptv-check /root/mylist.m3u
iptv-check: line 3: Beta: command not found
 IPTV-Check Tool"

Do I add to link in the iptv-check file somewhere or the terminal?

**Comment by peterpt** [comment]
Problem fixed , clone again the git and run the tool .
That error you had was my fault on writing the code but it is now solved .
