### ISSUE TITLE
Output file description missing ?

### ISSUE THREAD

**Issue by BasterdOperator** [peterpt/IPTV-CHECK#3]
Hey dude,

pretty handy script !

I noticed that in the output the line with the title/description from the orginal input file will be missing.

Put in a file like: (with a working channel)

lol.m3u
```
#EXTINF:-1,|BG| Super TV Channel 1
http://lolol.com:1234/live/123321/321123/52703.m3u8
```

and the script will only output the URL line , but not the line with the description. ("Super TV Channel 1")
The description line is needed for IPTV Clients.

The output file will look like:
`http://lolol.com:8789/live/123321/321123/52703.m3u8`

Can you replicate that issue?

**Comment by trello3** [comment]
> 
> 
> Hey dude,
> 
> pretty handy script !
> 
> I noticed that in the output the line with the title/description from the orginal input file will be missing.
> 
> Put in a file like: (with a working channel)
> 
> lol.m3u
> 
> ```
> #EXTINF:-1,|BG| Super TV Channel 1
> http://lolol.com:1234/live/123321/321123/52703.m3u8
> ```
> 
> and the script will only output the URL line , but not the line with the description. ("Super TV Channel 1")
> The description line is needed for IPTV Clients.
> 
> The output file will look like:
> `http://lolol.com:8789/live/123321/321123/52703.m3u8`
> 
> Can you replicate that issue?

Hey do you have telegram we can chat on? I want to update script but dont get what youre getting at.

**Comment by BasterdOperator** [comment]
I'm sorry no but i will prepare the input and output files and work on a better description. I will update this later.

**Comment by BasterdOperator** [comment]
Run these commands:
 ```
wget https://freedailyiptv.com/countries/World/World_freedailyiptv.com.m3u
./iptv-check World_freedailyiptv.com.m3u 

cat oklist.m3u 

#EXTM3U
  
https://59ef7ad665d1d.streamlock.net:1443/julieitalia/_definst_/julieitalia/playlist.m3u8?fluxustv.m3u8
 
 
http://122.155.180.8:5021/live/223
 
 
http://124.41.240.247:1935/live/mtv1/playlist.m3u8
 
 

```
1.) the oklist.m3u  will have empty lines
2.) All the lines with "#EXTINF:" are missing from oklist.m3u  They are needed for the IPtv clients. 

The output file should look like this:

#EXTM3U
#EXTINF:-1,julieitalia
https://59ef7ad665d1d.streamlock.net:1443/julieitalia/_definst_/julieitalia/playlist.m3u8?fluxustv.m3u8
#EXTINF:-1,Freedailyiptv.com
http://122.155.180.8:5021/live/223
#EXTINF:-1,mtv1
http://124.41.240.247:1935/live/mtv1/playlist.m3u8


Does this help?

**Comment by peterpt** [comment]
i made some changes in the code to fix your problem , however i am not sure if if dont get other problems ahead .
Anyway , the tool can check remote files directly except if they are too small like the one you are presenting .
